// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjN9PCHwcciMXJkEmXu32muMcDeurKDGM',
    appId: '1:574130960764:web:8e5369a8ca81e867be4cf9',
    messagingSenderId: '574130960764',
    projectId: 'test-notification-f1520',
    authDomain: 'test-notification-f1520.firebaseapp.com',
    storageBucket: 'test-notification-f1520.firebasestorage.app',
    measurementId: 'G-RSC2BJFJLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCa5EhiLtSHmSyEQD7tJfdkeoAVg8S8uw',
    appId: '1:574130960764:android:0f7fb66f33f9b39bbe4cf9',
    messagingSenderId: '574130960764',
    projectId: 'test-notification-f1520',
    storageBucket: 'test-notification-f1520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Ie2WVEok-IcpMXga6-BOQe4SLMNe6YQ',
    appId: '1:574130960764:ios:29ab1fbd772b3cbebe4cf9',
    messagingSenderId: '574130960764',
    projectId: 'test-notification-f1520',
    storageBucket: 'test-notification-f1520.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Ie2WVEok-IcpMXga6-BOQe4SLMNe6YQ',
    appId: '1:574130960764:ios:29ab1fbd772b3cbebe4cf9',
    messagingSenderId: '574130960764',
    projectId: 'test-notification-f1520',
    storageBucket: 'test-notification-f1520.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjN9PCHwcciMXJkEmXu32muMcDeurKDGM',
    appId: '1:574130960764:web:dd0e878f8fbbd414be4cf9',
    messagingSenderId: '574130960764',
    projectId: 'test-notification-f1520',
    authDomain: 'test-notification-f1520.firebaseapp.com',
    storageBucket: 'test-notification-f1520.firebasestorage.app',
    measurementId: 'G-88WL5KZ4R9',
  );
}
